version: '3.9'

services:
  todo-app:
    build: ./
    command: ./authenticator
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      SIGNING_KEY: "${SIGNING_KEY}"
      DATA_BASE_DSN: "${DATA_BASE_DSN}"

  db:
    restart: always
    image: postgres:latest
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5432:5432